version: "3.9"

services:

  test_authentification:
    #build:
    #context: .
    #dockerfile: Dockerfile
    image: e.papet/test_sentiments_analysis:1.0.0
    container_name: test_sentiment_authentification
    networks:
      - client_analysis
      - service_analysis
    volumes:
      - volume_data:/app
    environment:
      LOG: $LOG
      ROUTING_TEST: AUTHENTIFICATION
      FILE_LOG: $FILE_LOG
      HOST: $HOST
      PORT: $PORT
    depends_on:
      - api_service

  test_authorization:
    #build:
    #context: .
    #dockerfile: Dockerfile
    image: e.papet/test_sentiments_analysis:1.0.0
    container_name: test_sentiment_authorization
    networks:
      - client_analysis
      - service_analysis
    volumes:
      - volume_data:/app
    environment:
      LOG: $LOG
      ROUTING_TEST: AUTHORIZATION
      FILE_LOG: $FILE_LOG
      HOST: $HOST
      PORT: $PORT
    depends_on:
      - api_service
      - test_authentification

  test_content:
    #build:
    #context: .
    #dockerfile: Dockerfile
    image: e.papet/test_sentiments_analysis:1.0.0
    container_name: test_sentiment_content
    networks:
      - client_analysis
      - service_analysis
    volumes:
      - volume_data:/app
    environment:
      LOG: $LOG
      ROUTING_TEST: CONTENT
      FILE_LOG: $FILE_LOG
      HOST: $HOST
      PORT: $PORT
    depends_on:
      - api_service
      - test_authorization

  api_service:
    image: datascientest/fastapi:1.0.0
    container_name: service_api_analysis
    restart: always
    networks:
      - service_analysis

volumes:
  volume_data:
    driver: local
    #volume_authentification: 
    #driver: local
    #volume_authorization:
    #  driver: local
    #volume_content:
    #  driver: local

networks:
  client_analysis:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
  service_analysis:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
